CREATE or REPLACE PROCEDURE InsertOnCompra(p_id_compra NUMBER, P_ID_PASSAGEIRO PASSAGEIRO_TB.PK_CPF%TYPE, P_ID_PASSAGEM NUMBER) 
IS
DATA_COMPRA DATE;
BEGIN
    DATA_COMPRA:= SYSDATE;
	INSERT INTO COMPRA_TB VALUES (
    	tp_compra(
        	p_id_compra,
        	DATA_COMPRA, -- data_compra
        	(SELECT REF(p) FROM PASSAGEIRO_TB p WHERE p.PK_CPF = P_ID_PASSAGEIRO), -- passageiros REF
        	(SELECT REF(pt) FROM PASSAGEM pt WHERE pt.pk_localizador_passagem = P_ID_PASSAGEM) -- passagem REF
    	)
	);
END InsertOnCompra;

DELETE FROM COMPRA_TB;

EXEC INSERTONCOMPRA(1,'12345678901',1);

SELECT C.ID_COMPRA,DEREF(C.PASSAGEIROS).NOME,DEREF(C.PASSAGEM) FROM COMPRA_TB C;
