CREATE OR REPLACE TRIGGER DADO_INSERIDO_PASSAGEIRO
AFTER INSERT ON PASSAGEIRO_TB
FOR EACH ROW
BEGIN
    IF :NEW.SEXO = 'M' THEN 
    	DBMS_OUTPUT.PUT_LINE('SR. '||:NEW.NOME||' INSERIDO '||' CPF: '||:NEW.PK_CPF);
    ELSIF :NEW.SEXO = 'F' THEN
        DBMS_OUTPUT.PUT_LINE('SR. '||:NEW.NOME||' INSERIDO '||' CPF: '||:NEW.PK_CPF);
    END IF;
END DADO_INSERIDO_PASSAGEIRO;
/

SET SERVEROUTPUT ON;
