CREATE OR REPLACE TRIGGER DADO_INSERIDO_PASSAGEIRO
AFTER INSERT ON PASSAGEIRO_TB
FOR EACH ROW
BEGIN
    IF :NEW.SEXO = 'M' THEN 
    	DBMS_OUTPUT.PUT_LINE('SR. '||:NEW.NOME||' INSERIDO '||' CPF: '||:NEW.PK_CPF);
    ELSIF :NEW.SEXO = 'F' THEN
        DBMS_OUTPUT.PUT_LINE('SR. '||:NEW.NOME||' INSERIDO '||' CPF: '||:NEW.PK_CPF);
    END IF;
END DADO_INSERIDO_PASSAGEIRO;
/

SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER WHATS_UPDATED_PASSAGEIRO
BEFORE DELETE ON PASSAGEIRO_TB
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('PASSAGEIRO DE CPF ' || :OLD.PK_CPF || ' DELETADO');
END WHATS_UPDATED_PASSAGEIRO;
/

DELETE FROM PASSAGEIRO_TB WHERE PK_CPF = '98765432198';
