--DELETE FROM VOO_TABLE V WHERE V.PK_NUMERO_VOO = 7;

SELECT * FROM TABLE(SELECT P.TELEFONES FROM PASSAGEIRO_TB P WHERE P.PK_CPF = '99988877766');

SELECT T.ENDERECO_PAX.CIDADE, T.ENDERECO_PAX.ESTADO, T.ENDERECO_PAX.PAIS, T.ENDERECO_PAX.COMPLEMENTO FROM PASSAGEIRO_TB T WHERE T.PK_CPF = '99988877766';

UPDATE PASSAGEIRO_TB T SET T.ENDERECO_PAX.COMPLEMENTO = 'Av. Marechal Rondon' WHERE T.PK_CPF = '99988877766';
