--DELETE FROM VOO_TABLE V WHERE V.PK_NUMERO_VOO = 7;
SELECT * FROM PASSAGEIRO_TB;

SELECT P.NOME,P.PK_CPF FROM PASSAGEIRO_TB P WHERE P.NOME LIKE 'J%';

SELECT * FROM TABLE(SELECT P.TELEFONES FROM PASSAGEIRO_TB P WHERE P.PK_CPF = '99988877766');

SELECT T.ENDERECO_PAX.CIDADE, T.ENDERECO_PAX.ESTADO, T.ENDERECO_PAX.PAIS, T.ENDERECO_PAX.COMPLEMENTO FROM PASSAGEIRO_TB T WHERE T.PK_CPF = '99988877766';

UPDATE PASSAGEIRO_TB T SET T.ENDERECO_PAX.COMPLEMENTO = 'Av. Marechal Rondon' WHERE T.PK_CPF = '99988877766';

SELECT V.PK_NUMERO_VOO,V.ORIGEM,V.DESTINO,DEREF(R.PASSAGEM).PK_LOCALIZADOR_PASSAGEM,
DEREF(R.PASSAGEM).VALOR_PASSAGEM FROM VOO_TABLE V, TABLE(REFERE_SE) R;


SELECT ORIGEM, DESTINO, COUNT(*) AS QUANTIDADE, SUM(VALOR_PASSAGEM) AS VALOR_TOTAL_PASSAGEM, ROUND(AVG(VALOR_PASSAGEM),2) AS TICKET_MEDIO, MIN(VALOR_PASSAGEM)
AS VALOR_MINIMO_PASSAGEM, MAX(VALOR_PASSAGEM) AS VALOR_MAXIMO_PASSAGEM FROM
(SELECT V.PK_NUMERO_VOO,V.ORIGEM,V.DESTINO,DEREF(R.PASSAGEM).PK_LOCALIZADOR_PASSAGEM,
DEREF(R.PASSAGEM).VALOR_PASSAGEM AS VALOR_PASSAGEM FROM VOO_TABLE V, TABLE(REFERE_SE) R)
GROUP BY ORIGEM, DESTINO HAVING AVG(VALOR_PASSAGEM)>200 ORDER BY QUANTIDADE DESC;


SELECT C.ID_COMPRA,C.DATA_COMPRA,DEREF(C.PASSAGEIROS).PK_CPF,DEREF(C.PASSAGEM).PK_LOCALIZADOR_PASSAGEM FROM COMPRA_TB C
WHERE DEREF(C.PASSAGEIROS).PK_CPF IN (
SELECT P.PK_CPF FROM PASSAGEIRO_TB P
WHERE P.CALCULAR_IDADE() BETWEEN 26 AND 30);

---VIEW
CREATE VIEW VOOS_PARA_HOTEIS AS SELECT * FROM (SELECT V.ORIGEM,V.DESTINO,DEREF(REFE.PASSAGEM).PK_LOCALIZADOR_PASSAGEM AS PASSAGEM_LOCALIZADOR FROM VOO_TABLE V, TABLE(V.REFERE_SE) REFE) E
INNER JOIN (SELECT H.PKID_HOTEL,H.NOME, DEREF(G.COMPRAS).PASSAGEIROS.NOME, DEREF(G.COMPRAS).PASSAGEIROS.PK_CPF,
DEREF(G.COMPRAS).PASSAGEM.PK_LOCALIZADOR_PASSAGEM AS LOCALIZA_PASSAGEM FROM HOTEL H,
TABLE(H.REGISTROS) R, TABLE(DEREF(R.ESTADIAS).RESERVAS) G) L ON  E.PASSAGEM_LOCALIZADOR=L.LOCALIZA_PASSAGEM;

SELECT * FROM VOOS_PARA_HOTEIS;


SELECT ORIGEM, DESTINO, PASSAGEM_LOCALIZADOR FROM (SELECT * FROM (SELECT V.ORIGEM,V.DESTINO,DEREF(REFE.PASSAGEM).PK_LOCALIZADOR_PASSAGEM AS PASSAGEM_LOCALIZADOR FROM VOO_TABLE V, TABLE(V.REFERE_SE) REFE) E
FULL JOIN (SELECT H.PKID_HOTEL,H.NOME, DEREF(G.COMPRAS).PASSAGEIROS.NOME, DEREF(G.COMPRAS).PASSAGEIROS.PK_CPF,
DEREF(G.COMPRAS).PASSAGEM.PK_LOCALIZADOR_PASSAGEM AS LOCALIZA_PASSAGEM FROM HOTEL H,
TABLE(H.REGISTROS) R, TABLE(DEREF(R.ESTADIAS).RESERVAS) G) L ON  E.PASSAGEM_LOCALIZADOR=L.LOCALIZA_PASSAGEM) O WHERE O.NOME IS NULL;

(SELECT P.PK_CPF FROM PASSAGEIRO_TB P) MINUS (SELECT DEREF(R.COMPRAS).PASSAGEIROS.PK_CPF FROM ESTADIA E, TABLE(E.RESERVAS) R);

SELECT P.NOME, P.PK_CPF, P.CALCULAR_IDADE() AS IDADE FROM PASSAGEIRO_TB P WHERE P.CALCULAR_IDADE() > 
ALL (SELECT DEREF(R.COMPRAS).PASSAGEIROS.CALCULAR_IDADE() FROM ESTADIA E, TABLE(E.RESERVAS) R WHERE E.PK_COD_ESTADIA = 1);
