--DELETE FROM VOO_TABLE V WHERE V.PK_NUMERO_VOO = 7;

SELECT * FROM TABLE(SELECT P.TELEFONES FROM PASSAGEIRO_TB P WHERE P.PK_CPF = '99988877766');

SELECT T.ENDERECO_PAX.CIDADE, T.ENDERECO_PAX.ESTADO, T.ENDERECO_PAX.PAIS, T.ENDERECO_PAX.COMPLEMENTO FROM PASSAGEIRO_TB T WHERE T.PK_CPF = '99988877766';

UPDATE PASSAGEIRO_TB T SET T.ENDERECO_PAX.COMPLEMENTO = 'Av. Marechal Rondon' WHERE T.PK_CPF = '99988877766';

SELECT V.PK_NUMERO_VOO,V.ORIGEM,V.DESTINO,DEREF(R.PASSAGEM).PK_LOCALIZADOR_PASSAGEM,
DEREF(R.PASSAGEM).VALOR_PASSAGEM FROM VOO_TABLE V, TABLE(REFERE_SE) R;


SELECT ORIGEM, DESTINO, COUNT(*) AS QUANTIDADE, SUM(VALOR_PASSAGEM) AS VALOR_TOTAL_PASSAGEM, ROUND(AVG(VALOR_PASSAGEM),2) AS TICKET_MEDIO, MIN(VALOR_PASSAGEM)
AS VALOR_MINIMO_PASSAGEM, MAX(VALOR_PASSAGEM) AS VALOR_MAXIMO_PASSAGEM FROM
(SELECT V.PK_NUMERO_VOO,V.ORIGEM,V.DESTINO,DEREF(R.PASSAGEM).PK_LOCALIZADOR_PASSAGEM,
DEREF(R.PASSAGEM).VALOR_PASSAGEM AS VALOR_PASSAGEM FROM VOO_TABLE V, TABLE(REFERE_SE) R)
GROUP BY ORIGEM, DESTINO HAVING AVG(VALOR_PASSAGEM)>200 ORDER BY QUANTIDADE DESC;


SELECT C.ID_COMPRA,C.DATA_COMPRA,DEREF(C.PASSAGEIROS).PK_CPF,DEREF(C.PASSAGEM).PK_LOCALIZADOR_PASSAGEM FROM COMPRA_TB C
WHERE DEREF(C.PASSAGEIROS).PK_CPF IN (
SELECT P.PK_CPF FROM PASSAGEIRO_TB P
WHERE (P.CALCULAR_IDADE()<=30 AND P.CALCULAR_IDADE()>=26));
